# Generated by Django 6.0.3 on 2026-06-23 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprador',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, null=True, upload_to='pedidos/comprovantes/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprovante_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('criado', 'Criado'), ('aguardando_pagamento', 'Aguardando pagamento'), ('aguardando_aprovacao', 'Aguardando aprovação'), ('pago', 'Pago'), ('rejeitado', 'Rejeitado'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='criado', max_length=20),
        ),
        migrations.CreateModel(
            name='AvaliacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField()),
                ('comentario', models.TextField(blank=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_produtos', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='core.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='core.produto')),
            ],
            options={
                'ordering': ['-data_avaliacao', '-id'],
                'unique_together': {('comprador', 'produto', 'pedido')},
            },
        ),
    ]
