from django.urls import path

from .views import (
    ApiRootView,
    HealthCheckView,
    LoginView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    ProfileView,
    SellerStoreView,
    RegistroCompradorView,
    RegistroVendedorView,
    PublicStoreDetailView,
    PublicStoreListView,
    VendorCategoryDetailView,
    VendorCategoryListCreateView,
    VendorProductDetailView,
    VendorProductListCreateView,
    VendorProductPhotoDetailView,
    VendorProductPhotoUploadView,
    VendorProductVariationDetailView,
    VendorProductVariationListCreateView,
    buyer_dashboard_page,
    forgot_password_page,
    home_page,
    login_page,
    profile_page,
    product_page,
    register_page,
    search_page,
    seller_dashboard_page,
    seller_products_page,
    seller_store_page,
    store_page,
)

urlpatterns = [
    path('', ApiRootView.as_view(), name='api-root'),
    path('health/', HealthCheckView.as_view(), name='health-check'),
    path('auth/register/vendor/', RegistroVendedorView.as_view(), name='register-vendor'),
    path('auth/register/buyer/', RegistroCompradorView.as_view(), name='register-buyer'),
    path('auth/login/', LoginView.as_view(), name='auth-login'),
    path('auth/profile/', ProfileView.as_view(), name='auth-profile'),
    path('auth/password-reset/request/', PasswordResetRequestView.as_view(), name='password-reset-request'),
    path('auth/password-reset/confirm/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('seller/store/', SellerStoreView.as_view(), name='seller-store'),
    path('seller/categories/', VendorCategoryListCreateView.as_view(), name='seller-categories'),
    path('seller/categories/<int:category_id>/', VendorCategoryDetailView.as_view(), name='seller-category-detail'),
    path('seller/products/', VendorProductListCreateView.as_view(), name='seller-products'),
    path('seller/products/<int:product_id>/', VendorProductDetailView.as_view(), name='seller-product-detail'),
    path('seller/products/<int:product_id>/photos/', VendorProductPhotoUploadView.as_view(), name='seller-product-photos'),
    path('seller/products/<int:product_id>/variations/', VendorProductVariationListCreateView.as_view(), name='seller-product-variations'),
    path('seller/product-photos/<int:photo_id>/', VendorProductPhotoDetailView.as_view(), name='seller-product-photo-detail'),
    path('seller/product-variations/<int:variation_id>/', VendorProductVariationDetailView.as_view(), name='seller-product-variation-detail'),
    path('lojas/', PublicStoreListView.as_view(), name='public-stores'),
    path('lojas/<int:store_id>/', PublicStoreDetailView.as_view(), name='public-store-detail'),
    path('front/', home_page, name='front-home'),
    path('front/busca/', search_page, name='front-search'),
    path('front/loja/<slug:slug>/', store_page, name='front-store'),
    path('front/produto/<slug:slug>/', product_page, name='front-product'),
    path('front/vendedor/', seller_dashboard_page, name='front-seller-dashboard'),
    path('front/minha-loja/', seller_store_page, name='front-seller-store'),
    path('front/meus-produtos/', seller_products_page, name='front-seller-products'),
    path('front/comprador/', buyer_dashboard_page, name='front-buyer-dashboard'),
    path('front/login/', login_page, name='front-login'),
    path('front/cadastro/', register_page, name='front-register'),
    path('front/recuperar-senha/', forgot_password_page, name='front-forgot-password'),
    path('front/perfil/', profile_page, name='front-profile'),
]
